# Generated by Django 4.0.3 on 2022-04-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='edad_cand',
            field=models.IntegerField(verbose_name=4),
        ),
    ]
