# Generated by Django 4.0.3 on 2022-04-09 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_alter_candidato_edad_cand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cand', models.CharField(max_length=100)),
                ('ape_cand', models.CharField(max_length=100)),
                ('edad_cand', models.IntegerField(verbose_name=4)),
            ],
        ),
        migrations.CreateModel(
            name='Region2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_nom', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='candidato2',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.region2'),
        ),
    ]
